FROM python:3.11-slim

WORKDIR /app
COPY pyproject.toml README.md .
RUN pip install --no-cache-dir pip setuptools wheel && pip install --no-cache-dir -e .[dev]
COPY app app
COPY migrations migrations
CMD ["celery", "-A", "app.workers.tasks.celery_app", "worker", "-Q", "trades", "-l", "info"]
